### ISSUE TITLE
Not really an issue but...

### ISSUE THREAD

**Issue by RoYoshi** [Mikusch/tf-bhop#12]
I read thru the whole thing and still can't get the plugin to work, mind if you tell me if I have to do something cause i put every file where they are supposed to go

**Comment by Mikusch** [comment]
I can't really do much with "can't get the plugin to work". Do you get any error messages? What have you tried to resolve the issue?

In any case, there are installation instructions on the [AlliedModders forum post](https://forums.alliedmods.net/showthread.php?t=330054).

**Comment by RoYoshi** [comment]
aww thanks, i recently got into making a private server so i am new to adding plugins
