### ISSUE TITLE
SMX included in latest release breaks jumping.

### ISSUE THREAD

**Issue by AndrewBetson** [Mikusch/tf-bhop#13]
The SMX included in the latest release of this plugin has an odd bug that pushes players in the opposite direction when jumping. Compiling the plugin with either the latest SM 1.10 or SM 1.11 compilers seems to resolve this bug with 0 code changes.

Attached are an example video demonstrating the bug as well as a screenshot of the cryptic errors logged by the server when this bug occurs.

Note that in the attached video, I only ever hold one directional movement key at a time, and never crouch.

https://user-images.githubusercontent.com/7203160/179827665-d977c0bd-9daf-4b86-a76a-436ea5926cbe.mp4

![cryptic_errors](https://user-images.githubusercontent.com/7203160/179826646-9a040bb2-9174-4f4f-8925-3b37084a71ed.png)

**Comment by Mikusch** [comment]
Hi, thanks for the report. I am not sure what went wrong there, but I've updated the release package with a new plugin binary.

I don't really have a server available at the moment to test it out, could you check if it works now?

**Comment by AndrewBetson** [comment]
The updated plugin binary no longer has this issue. Thanks for the quick fix!
