### ISSUE TITLE
Plugin BASICALLY doesn't do anything beside ABH. 

### ISSUE THREAD

**Issue by yplebedev** [Mikusch/tf-bhop#16]
Upon loading the server, or reloading plugins, an error appears:

**[tf-bhop.smx] Failed to verify memory patch CTFGameMovement::PreventBunnyJumping::AllowBunnyJumping**

Ingame, it doesn't seem to be too different from doing it on vanilla, such as in casual, aside from the more or less consistent perfect hops. Maybe I did something wrong, but I HAVE followed install instructions 1:1.

**Comment by Mikusch** [comment]
I assume you've downloaded the release version from GitHub which been outdated for ~3 years. The repository files were more up to date. I've published a new release since this seems to be a common mistake, let me know if that fixed your problem.

**Comment by yplebedev** [comment]
IM FAST AS FUCK! It works, thanks! Also, DAMN, thing's OLDDD.
